# fly.toml app configuration file generated for uobattendancecodedatabase on 2024-10-20T19:13:49+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uobattendancecodedatabase'
primary_region = 'lhr'

[build]

[[mounts]]
  source = 'db'
  destination = '/app/db'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
